import 'bootstrap/dist/css/bootstrap.min.css';
import Header from "./components/Header/page";
import "./globals.css";

export const metadata = {
  title: "MyTube",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <section className="main">
          <Header />
          {children}
        </section>
      </body>
    </html>
  );
}
